import type { ResolvedFile } from '../resolver.js';
import { generateTables } from './tables.js';
import { generateDerivedViews, generateRefinementViews } from './views.js';
import { generateGuards } from './guards.js';
import { generateTriggers } from './triggers.js';
import { generateOutboxTable } from './outbox.js';

export function generateSql(resolved: ResolvedFile): string {
  const sections = [
    '-- Generated by the Velle proof-of-concept compiler. Do not edit by hand.',
    '-- ---- Tables ----',
    generateTables(resolved),
    '-- ---- Derived-property views ----',
    generateDerivedViews(resolved),
    '-- ---- Refinement views ----',
    generateRefinementViews(resolved),
    '-- ---- produces guards (UNIQUE constraints) ----',
    generateGuards(resolved),
    '-- ---- Effects outbox ----',
    generateOutboxTable(),
    '-- ---- Entering-refinement triggers ----',
    generateTriggers(resolved),
  ];
  return sections.filter((s) => s.trim().length > 0).join('\n\n') + '\n';
}
