// The enrollment example's transpile output: developer-owned generated source
// and the tests that drive it. This example exercises the collection constructs
// of README §6 — declared `many` (m2m), `many <scalar>`, reference-set acts,
// whole-set replacement, `+`/`-`, fan-out assignment, and derived collection
// views. Regenerated by `gradle generate`.
plugins {
    kotlin("jvm")
}

group = "velle"

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":compiler"))
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

tasks.register<JavaExec>("generate") {
    description = "Regenerate the Enrollment typed surface and executable specs from enrollment.velle"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("velle.GenerateKt")
    args("../enrollment.velle", "Enrollment")
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
