# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/ActiveMemberSpec.kt. Regenerate with: gradle generate
Feature: ActiveMember

  # rule RenewMembership
  Scenario: At the Monthly tick, an ActiveMember produces a Charge
    Given one member in "ActiveMember", no "Monthly" tick yet
    When "Monthly" ticks
    Then one more "Charge" exists
    And that Charge's "member" is the member
    And another "Monthly" tick produces nothing more
    And after 31 days pass, "Monthly" produces another "Charge"

  # rule ApplyCharge
  Scenario: A new UnappliedCharge produces a ChargeApplication and sets member.balance after the commit
    When a commit brings one new charge into "UnappliedCharge"
    Then the rule has fired after that transaction
    And one more "ChargeApplication" exists
    And that ChargeApplication's "charge" is the charge
    And the charge has left "UnappliedCharge"
    And another "Hourly" tick produces nothing more
