# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/ChronicDelinquentSpec.kt. Regenerate with: gradle generate
Feature: ChronicDelinquent

  # rule OpenAccountReview
  Scenario: A new ChronicDelinquent produces an AuditEntry and an AccountReview
    When a commit brings one new member into "ChronicDelinquent"
    Then one more "AuditEntry" exists
    And that AuditEntry's "member" is the member
    And one more "AccountReview" exists
    And that AccountReview's "member" is the member
    And another "Daily" tick produces nothing more
