-- Generated by the Velle proof-of-concept compiler. Do not edit by hand.

-- ---- Tables ----

CREATE TABLE customers (
  id bigserial PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL
);

CREATE TABLE invoices (
  id bigserial PRIMARY KEY,
  customer_id bigint REFERENCES customers(id) NOT NULL,
  amount numeric(14,2) NOT NULL,
  due date NOT NULL
);

CREATE TABLE orders (
  id bigserial PRIMARY KEY,
  customer_id bigint REFERENCES customers(id) NOT NULL,
  invoice_id bigint REFERENCES invoices(id) NOT NULL,
  amount numeric(14,2) NOT NULL
);

CREATE TABLE charge_responses (
  id bigserial PRIMARY KEY,
  outcome text NOT NULL,
  processed_on date NOT NULL
);

CREATE TABLE charge_attempts (
  id bigserial PRIMARY KEY,
  order_id bigint REFERENCES orders(id) NOT NULL,
  requested_on date NOT NULL,
  response_id bigint REFERENCES charge_responses(id)
);

CREATE TABLE payments (
  id bigserial PRIMARY KEY,
  invoice_id bigint REFERENCES invoices(id) NOT NULL,
  charge_attempt_id bigint REFERENCES charge_attempts(id),
  amount numeric(14,2) NOT NULL,
  received_on date NOT NULL
);

CREATE TABLE refunds (
  id bigserial PRIMARY KEY,
  payment_id bigint REFERENCES payments(id) NOT NULL,
  amount numeric(14,2) NOT NULL,
  refunded_on date NOT NULL
);

CREATE TABLE audit_log_entries (
  id bigserial PRIMARY KEY,
  order_id bigint REFERENCES orders(id) NOT NULL,
  logged_on date NOT NULL
);

CREATE TABLE receipts (
  id bigserial PRIMARY KEY,
  invoice_id bigint REFERENCES invoices(id) NOT NULL,
  sent_on date NOT NULL
);

CREATE TABLE inventory_releases (
  id bigserial PRIMARY KEY,
  order_id bigint REFERENCES orders(id) NOT NULL,
  released_on date NOT NULL
);

-- ---- Derived-property views ----

CREATE VIEW invoices_derived AS
SELECT t.*,
  ((t.amount - COALESCE((SELECT sum(amount) FROM payments WHERE invoice_id = t.id), 0)) + COALESCE((SELECT sum(amount) FROM refunds WHERE payment_id IN (SELECT id FROM payments WHERE invoice_id = t.id)), 0)) AS balance
FROM invoices t;

-- ---- Refinement views ----

CREATE VIEW settled_invoice AS
SELECT * FROM invoices_derived t
WHERE t.balance <= 0;

CREATE VIEW pending_charge_attempt AS
SELECT * FROM charge_attempts t
WHERE t.response_id IS NULL;

CREATE VIEW completed_charge_attempt AS
SELECT * FROM charge_attempts t
WHERE t.response_id IS NOT NULL;

CREATE VIEW successful_charge AS
SELECT * FROM charge_attempts t
WHERE t.response_id IS NOT NULL
  AND (SELECT outcome FROM charge_responses WHERE id = t.response_id) = 'approved';

CREATE VIEW failed_charge AS
SELECT * FROM charge_attempts t
WHERE t.response_id IS NOT NULL
  AND (SELECT outcome FROM charge_responses WHERE id = t.response_id) = 'declined';

-- ---- produces guards (UNIQUE constraints) ----

ALTER TABLE charge_attempts ADD CONSTRAINT charge_attempts_order_unique UNIQUE (order_id);
ALTER TABLE payments ADD CONSTRAINT payments_charge_attempt_unique UNIQUE (charge_attempt_id);
ALTER TABLE inventory_releases ADD CONSTRAINT inventory_releases_order_unique UNIQUE (order_id);
ALTER TABLE receipts ADD CONSTRAINT receipts_invoice_unique UNIQUE (invoice_id);

-- ---- Effects outbox ----

CREATE TABLE effects_outbox (
  id bigserial PRIMARY KEY,
  effect_name text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);

-- ---- Entering-refinement triggers ----

CREATE OR REPLACE FUNCTION trg_orders_check() RETURNS trigger AS $$
DECLARE
  affected_id bigint;
BEGIN
    affected_id := NEW.id;
    IF affected_id IS NOT NULL
       AND TRUE
       AND NOT EXISTS (SELECT 1 FROM charge_attempts WHERE order_id = affected_id)
    THEN
      INSERT INTO effects_outbox (effect_name, payload)
      VALUES ('InitiateCharge', jsonb_build_object('root_id', affected_id));
    END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER orders_after_write
AFTER INSERT OR UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION trg_orders_check();

CREATE OR REPLACE FUNCTION trg_charge_attempts_check() RETURNS trigger AS $$
DECLARE
  affected_id bigint;
BEGIN
    affected_id := NEW.id;
    IF affected_id IS NOT NULL
       AND EXISTS (SELECT 1 FROM successful_charge WHERE id = affected_id)
       AND NOT EXISTS (SELECT 1 FROM payments WHERE charge_attempt_id = affected_id)
    THEN
      INSERT INTO effects_outbox (effect_name, payload)
      VALUES ('RecordPayment', jsonb_build_object('root_id', affected_id));
    END IF;
    affected_id := NEW.id;
    IF affected_id IS NOT NULL
       AND EXISTS (SELECT 1 FROM failed_charge WHERE id = affected_id)
       AND NOT EXISTS (SELECT 1 FROM inventory_releases WHERE order_id = affected_id)
    THEN
      INSERT INTO effects_outbox (effect_name, payload)
      VALUES ('ReleaseInventory', jsonb_build_object('root_id', affected_id));
    END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER charge_attempts_after_write
AFTER INSERT OR UPDATE ON charge_attempts
FOR EACH ROW EXECUTE FUNCTION trg_charge_attempts_check();

CREATE OR REPLACE FUNCTION trg_invoices_check() RETURNS trigger AS $$
DECLARE
  affected_id bigint;
BEGIN
    affected_id := NEW.id;
    IF affected_id IS NOT NULL
       AND EXISTS (SELECT 1 FROM settled_invoice WHERE id = affected_id)
       AND NOT EXISTS (SELECT 1 FROM receipts WHERE invoice_id = affected_id)
    THEN
      INSERT INTO effects_outbox (effect_name, payload)
      VALUES ('SendReceipt', jsonb_build_object('root_id', affected_id));
    END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER invoices_after_write
AFTER INSERT OR UPDATE ON invoices
FOR EACH ROW EXECUTE FUNCTION trg_invoices_check();

CREATE OR REPLACE FUNCTION trg_payments_check() RETURNS trigger AS $$
DECLARE
  affected_id bigint;
BEGIN
    affected_id := NEW.invoice_id;
    IF affected_id IS NOT NULL
       AND EXISTS (SELECT 1 FROM settled_invoice WHERE id = affected_id)
       AND NOT EXISTS (SELECT 1 FROM receipts WHERE invoice_id = affected_id)
    THEN
      INSERT INTO effects_outbox (effect_name, payload)
      VALUES ('SendReceipt', jsonb_build_object('root_id', affected_id));
    END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER payments_after_write
AFTER INSERT OR UPDATE ON payments
FOR EACH ROW EXECUTE FUNCTION trg_payments_check();

CREATE OR REPLACE FUNCTION trg_refunds_check() RETURNS trigger AS $$
DECLARE
  affected_id bigint;
BEGIN
    affected_id := (SELECT invoice_id FROM payments WHERE id = NEW.payment_id);
    IF affected_id IS NOT NULL
       AND EXISTS (SELECT 1 FROM settled_invoice WHERE id = affected_id)
       AND NOT EXISTS (SELECT 1 FROM receipts WHERE invoice_id = affected_id)
    THEN
      INSERT INTO effects_outbox (effect_name, payload)
      VALUES ('SendReceipt', jsonb_build_object('root_id', affected_id));
    END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER refunds_after_write
AFTER INSERT OR UPDATE ON refunds
FOR EACH ROW EXECUTE FUNCTION trg_refunds_check();
