# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/ArchivedInvoiceSpec.kt. Regenerate with: gradle generate
Feature: ArchivedInvoice

  # rule NoteUnarchival
  Scenario: An UnarchiveRequest for an ArchivedInvoice produces an UnarchiveNotice
    Given a member of "ArchivedInvoice"
    When a "UnarchiveRequest" for it is committed
    Then it is no longer a "ArchivedInvoice"
    And one more "UnarchiveNotice" exists
    And that UnarchiveNotice's "invoice" is the invoice
