# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/CorrectEmailSpec.kt. Regenerate with: gradle generate
Feature: CorrectEmail

  # rule ApplyEmailCorrection
  Scenario: A new CorrectEmail sets customer.email
    When a commit brings one new correctEmail into "CorrectEmail"
    Then the customer.email now equals the act's "corrected"
