package velle

/**
 * MockHarness codegen (README §22, the milestone scope statement): transpiles a
 * spec to a typed Kotlin surface over the runtime — one commit function per
 * exposed shape, one tick function per schedule, typed views per shape and
 * refinement, membership tests, and a `main` for driving the system manually.
 * A spike: sugar over VelleSystem, not a standalone compilation.
 */
object Codegen {

    fun generate(specSource: String, systemName: String, packageName: String = "velle.generated"): String {
        val model = Model(Parser.parse(specSource))
        require(model.diagnostics.isEmpty()) { "spec does not resolve: ${model.diagnostics}" }
        return Emitter(model, specSource, systemName, packageName).emit()
    }

    private class Emitter(
        val model: Model,
        val spec: String,
        val name: String,
        val pkg: String,
    ) {
        val sb = StringBuilder()
        fun line(s: String = "") { sb.append(s).append('\n') }

        val schedules: List<String> = model.rules.values
            .flatMap { it.triggers }.filter { it != "commit" }.distinct()

        val domains = DomainAnalysis(model)

        fun emit(): String {
            header()
            line("class ${name}System(startTime: Instant = Instant.parse(\"2026-01-01T09:00:00Z\")) {")
            line()
            line("    val system: VelleSystem = VelleSystem(Model(Parser.parse(SPEC)), startTime)")
            line()
            clock()
            ticks()
            closureInputTypes()
            model.exposed.forEach { commitFn(it) }
            model.shapes.keys.forEach { shapeAccessors(it) }
            model.refinements.keys.forEach { refinementAccessors(it) }
            model.shapes.keys.forEach { shapeView(it) }
            model.refinements.keys.forEach { refinementView(it) }
            specConstant()
            line("}")
            mainFn()
            return sb.toString()
        }

        fun header() {
            line("// GENERATED by Velle MockHarness from ${name.lowercase()}.velle — do not edit.")
            line("// Regenerate with: gradle generate")
            line("package $pkg")
            line()
            line("import velle.*")
            line("import java.math.BigDecimal")
            line("import java.time.Instant")
            line("import java.time.LocalDate")
            line()
        }

        fun clock() {
            line("    // ── clock (harness-controlled; ticks are separate calls) ──")
            line("    val now: Instant get() = system.now")
            line("    fun advanceSeconds(seconds: Long) = system.advance(seconds)")
            line("    fun advanceDays(days: Long) = system.advanceDays(days)")
            line("    fun setTime(t: Instant) = system.setTime(t)")
            line()
        }

        fun ticks() {
            if (schedules.isEmpty()) return
            line("    // ── ticks: scheduled events and user acts are both external input ──")
            schedules.forEach { line("    fun tick$it() = system.tick(\"$it\")") }
            line()
        }

        // ── the exposure closure: nested input types (README §6, "Inline part
        // creation") — the projection, not the mirror: no `id`, no back-reference
        // (language-populated); an out-of-closure relationship stays a typed view
        // (the reference handle), an in-closure edge is a nested input value. ──

        /** structural signature (prop name excluded) → generated class name */
        val closureNames = linkedMapOf<ClosureEdge, String>()

        fun closureClassName(edge: ClosureEdge): String {
            val sig = edge.copy(prop = "")
            closureNames[sig]?.let { return it }
            var name = "New${edge.partShape}"
            if (name in closureNames.values)
                name = "New${edge.partShape}Via${edge.backRef.replaceFirstChar { it.uppercase() }}"
            var n = 2
            while (name in closureNames.values) name = "New${edge.partShape}${n++}"
            closureNames[sig] = name
            return name
        }

        fun emitClosureClass(name: String, edge: ClosureEdge) {
            val decl = model.shapes.getValue(edge.partShape)
            val stored = decl.members.filterIsInstance<StoredProp>().filter { it.name != edge.backRef }
            val required = stored.filter { it.initially == null && !isOptional(it.type) }
            val optional = stored.filter { it.initially != null || isOptional(it.type) }
            val hasParams = required.isNotEmpty() || optional.isNotEmpty() || edge.children.isNotEmpty()
            if (!hasParams) {
                line("    class $name { internal fun raw(): Map<String, Any?> = emptyMap() }")
                line()
                return
            }
            line("    data class $name(")
            required.forEach { line("        val ${it.name}: ${paramType(it.type)},") }
            optional.forEach { line("        val ${it.name}: ${paramType(it.type).removeSuffix("?")}? = null,") }
            edge.children.forEach { line("        val ${it.prop}: List<${closureClassName(it)}> = emptyList(),") }
            line("    ) {")
            line("        internal fun raw(): Map<String, Any?> = buildMap {")
            required.forEach { line("            put(\"${it.name}\", ${rawExpr(it.name, it.type)})") }
            optional.forEach { line("            ${it.name}?.let { put(\"${it.name}\", ${rawExpr("it", it.type)}) }") }
            edge.children.forEach { line("            put(\"${it.prop}\", ${it.prop}.map { it.raw() })") }
            line("        }")
            line("    }")
            line()
        }

        fun closureInputTypes() {
            val toEmit = linkedMapOf<String, ClosureEdge>()
            fun visit(edge: ClosureEdge) {
                edge.children.forEach { visit(it) }
                toEmit.putIfAbsent(closureClassName(edge), edge)
            }
            model.exposed.forEach { shape -> model.closures[shape].orEmpty().forEach { visit(it) } }
            if (toEmit.isEmpty()) return
            line("    // ── closure input values (README §6, \"Inline part creation\") ──")
            for ((name, edge) in toEmit) emitClosureClass(name, edge)
        }

        fun commitFn(shape: String) {
            queueKeyDoc(shape)
            val stored = model.shapes.getValue(shape).members.filterIsInstance<StoredProp>()
            val required = stored.filter { it.initially == null && !isOptional(it.type) }
            val optional = stored.filter { it.initially != null || isOptional(it.type) }
            val edges = model.closures[shape].orEmpty()
            val params = required.map { "${it.name}: ${paramType(it.type)}" } +
                optional.map { "${it.name}: ${paramType(it.type).removeSuffix("?")}? = null" } +
                edges.map { "${it.prop}: List<${closureClassName(it)}> = emptyList()" }
            line("    fun commit$shape(${params.joinToString(", ")}): CommitResult =")
            line("        system.commit(\"$shape\", buildMap {")
            required.forEach { line("            put(\"${it.name}\", ${rawExpr(it.name, it.type)})") }
            optional.forEach { line("            ${it.name}?.let { put(\"${it.name}\", ${rawExpr("it", it.type)}) }") }
            if (edges.isEmpty()) {
                line("        })")
            } else {
                line("        }, buildMap {")
                edges.forEach { line("            put(\"${it.prop}\", ${it.prop}.map { it.raw() })") }
                line("        })")
            }
            line()
        }

        /** The serialization contract (OQ40): the queue keys this commit's work
         *  joins, stated on the generated surface so the engineer reads them
         *  off the contract instead of re-deriving them from the rule graph. */
        fun queueKeyDoc(shape: String) {
            val domain = domains.actDomains[shape] ?: return
            val keys = domain.renderKeys(shape.replaceFirstChar { it.lowercase() })
            line("    /** ${queueKeyLead(domain, keys)}")
            for (w in domain.widenings) {
                val status = if (w.tolerated) "tolerated by ${w.declaration}" else "unexamined (A5)"
                line("     *  System-wide over ${w.shape} — ${w.cause} ($status).")
            }
            line("     *  Commits sharing a queue key are handled one at a time, in arrival")
            line("     *  order (U3); commits whose keys are disjoint run in parallel. */")
        }

        fun queueKeyLead(domain: SerializationDomain, keys: List<String>): String = when {
            domain.wide && keys.isEmpty() -> "Queue: system-wide."
            domain.wide -> "Queue keys: ${keys.joinToString(", ") { "[$it]" }} — plus system-wide width below."
            keys.isEmpty() -> "Queue keys: none — this commit contends with no other work."
            else -> "Queue ${if (keys.size == 1) "key" else "keys"}: ${keys.joinToString(", ") { "[$it]" }}."
        }

        fun shapeAccessors(shape: String) {
            if (shape in model.transients) return // an input to the state, never readable after its commit
            line("    fun ${plural(shape)}(): List<${shape}View> = system.instancesOf(\"$shape\").map { ${shape}View(it) }")
            line("    fun ${decap(shape)}(id: Long) = ${shape}View(id)")
        }

        fun refinementAccessors(ref: String) {
            val base = model.baseOf(ref) ?: return
            if (base in model.transients) return
            line("    fun ${plural(ref)}(): List<${ref}View> = system.instancesOf(\"$ref\").map { ${ref}View(it) }")
            line("    fun ${base}View.is$ref(): Boolean = system.isMember(id, \"$ref\")")
        }

        fun shapeView(shape: String) {
            if (shape in model.transients) return
            line()
            line("    inner class ${shape}View(override val id: Long) : View {")
            for ((memberName, m) in model.membersOf(shape)) {
                if (memberName == "id") continue
                line("        val $memberName: ${kotlinType(m.type)} get() = ${readExpr("system.get(id, \"$memberName\")", m.type)}")
            }
            line("        override fun toString() = \"$shape#\$id\"")
            line("        override fun equals(other: Any?) = other is ${shape}View && other.id == id")
            line("        override fun hashCode() = id.hashCode()")
            line("    }")
        }

        fun refinementView(ref: String) {
            val base = model.baseOf(ref) ?: return
            if (base in model.transients) return
            val own = model.refinements.getValue(ref).members.filterIsInstance<DerivedProp>()
            line()
            line("    inner class ${ref}View(override val id: Long) : View {")
            line("        fun as$base() = ${base}View(id)")
            for (m in own) {
                val t = model.typeOf(m.type)
                line("        val ${m.name}: ${kotlinType(t)} get() = ${readExpr("system.getAs(id, \"$ref\", \"${m.name}\")", t)}")
            }
            line("        override fun toString() = \"$ref#\$id\"")
            line("    }")
        }

        fun specConstant() {
            line()
            line("    companion object {")
            line("        private val SPEC = \"\"\"")
            spec.trimEnd().lines().forEach { line(it) }
            line("\"\"\"")
            line("    }")
        }

        fun mainFn() {
            line()
            line("fun main() {")
            line("    val sys = ${name}System()")
            line("    println(\"Velle MockHarness — $name\")")
            line("    println(\"Commits: ${model.exposed.joinToString(", ") { "commit$it(...)" }}\")")
            if (schedules.isNotEmpty())
                line("    println(\"Ticks: ${schedules.joinToString(", ") { "tick$it()" }}\")")
            line("    println(\"Edit this main to drive the system; state prints below.\")")
            line()
            line("    // <your scenario here>")
            line()
            model.shapes.keys.filterNot { it in model.transients }.forEach {
                line("    println(\"$it: \" + sys.${plural(it)}().size)")
            }
            line("}")
        }

        // ── type mapping ─────────────────────────────────────────────────────

        fun isOptional(t: TypeRef) = (t as? ScalarType)?.optional == true || (t as? RelType)?.optional == true

        /** Parameter type for a commit function (relationships take views; `many` takes lists). */
        fun paramType(t: TypeRef): String = when (t) {
            is RelType ->
                if (t.many) "List<${t.shape}View>"
                else "${t.shape}View" + if (t.optional) "?" else ""
            is ScalarType ->
                if (t.many) "List<${scalarKotlin(t.name)}>"
                else scalarKotlin(t.name) + if (t.optional) "?" else ""
        }

        /** Convert a parameter back to the raw value the runtime accepts. */
        fun rawExpr(expr: String, t: TypeRef): String = when (t) {
            is RelType -> if (t.many) "$expr.map { it.id }" else "$expr.id"
            is ScalarType -> expr
        }

        fun scalarKotlin(name: String): String = when (name) {
            "text" -> "String"
            "integer" -> "Int"
            "long" -> "Long"
            "decimal" -> "BigDecimal"
            "double" -> "Double"
            "boolean" -> "Boolean"
            "Date" -> "LocalDate"
            "DateTime" -> "Instant"
            else -> "Any"
        }

        fun kotlinType(t: VType): String = when (t) {
            is VType.Num -> scalarKotlin(t.name)
            VType.Text -> "String"
            VType.Bool -> "Boolean"
            VType.DateT -> "LocalDate"
            VType.DateTimeT -> "Instant"
            is VType.Inst -> "${t.shape}View"
            is VType.Coll -> "List<${t.shape}View>"
            is VType.CollS -> "List<${scalarKotlin(t.name)}>"
            is VType.Optional -> kotlinType(t.inner) + "?"
            VType.Id, VType.Unknown -> "Any"
        }

        /** Expression converting a raw runtime read into the typed surface. */
        fun readExpr(call: String, t: VType): String = when (t) {
            is VType.Num -> when (t.name) {
                "integer" -> "($call as BigDecimal).intValueExact()"
                "long" -> "($call as BigDecimal).longValueExact()"
                "double" -> "($call as BigDecimal).toDouble()"
                else -> "$call as BigDecimal"
            }
            VType.Text -> "$call as String"
            VType.Bool -> "$call as Boolean"
            VType.DateT -> "$call as LocalDate"
            VType.DateTimeT -> "$call as Instant"
            is VType.Inst -> "${t.shape}View($call as Long)"
            is VType.Coll -> "($call as List<*>).map { ${t.shape}View(it as Long) }"
            is VType.CollS -> when (t.name) {
                "integer" -> "($call as List<*>).map { (it as BigDecimal).intValueExact() }"
                "long" -> "($call as List<*>).map { (it as BigDecimal).longValueExact() }"
                "double" -> "($call as List<*>).map { (it as BigDecimal).toDouble() }"
                "decimal" -> "($call as List<*>).map { it as BigDecimal }"
                else -> "($call as List<*>).map { it as ${scalarKotlin(t.name)} }"
            }
            is VType.Optional -> when (val inner = t.inner) {
                is VType.Inst -> "($call as Long?)?.let { ${inner.shape}View(it) }"
                else -> "$call as ${kotlinType(t)}"
            }
            VType.Id, VType.Unknown -> call
        }

        fun decap(s: String) = s.replaceFirstChar { it.lowercase() }
        fun plural(s: String) = decap(s) + "s"
    }
}
