package velle

/**
 * Sequence-diagram emission (working-docs/questions/OQ41, tier 1): a markdown
 * document of Mermaid fences, one diagram per exposed act, derived from the
 * same model the validator checks — a deterministic projection of the spec,
 * never authored by hand.
 *
 * What a diagram shows is the act's **may-fire cascade**: the transaction
 * envelope as a `critical` frame (everything inside stands or falls together),
 * in-envelope rule firings with their conditions visible as notes, `after
 * commit` boundaries as async arrows into their own frames, backstop schedules
 * as `loop` blocks, and the transaction-end `never` checks that guard the
 * envelope. Conditions the compiler cannot resolve statically stay visible as
 * "when <condition>" notes — the diagram says what *may* happen, never what
 * will.
 *
 * The firing test is deliberately an over-approximation of V3's (creates also
 * count field owners and collection shapes, matching the runtime's relevance
 * gating): a diagram that omits a possible firing lies, one that shows an
 * unreachable branch merely hedges — so uncertainty errs toward showing.
 */
object DiagramGen {

    fun generate(source: String, systemName: String): String {
        val model = Model(Parser.parse(source))
        return buildString {
            appendLine("# Sequence diagrams — $systemName")
            appendLine()
            appendLine(
                "Generated from the spec — a deterministic projection, regenerated by `gradle generate`; " +
                    "do not edit. One diagram per exposed act. Each diagram is **may-fire**: a rule appears " +
                    "wherever the commit could affect its condition, with the condition shown as a note — " +
                    "whether it actually fires depends on the data at that commit. Frames (`critical`) are " +
                    "transaction envelopes: everything inside one frame stands or falls together."
            )
            for (act in model.exposed) {
                appendLine()
                appendLine("## commit$act")
                appendLine()
                appendLine("```mermaid")
                append(ActDiagram(model, systemName, act).render())
                appendLine("```")
            }
        }
    }

    // ── one act's cascade ────────────────────────────────────────────────────

    private sealed interface Kind {
        data class Create(val shape: String) : Kind
        data class Assign(val shape: String, val field: String) : Kind
    }

    private class ActDiagram(val model: Model, val systemName: String, val act: String) {

        private val sb = StringBuilder()
        private val fired = mutableSetOf<String>()
        private var txnCount = 0
        /** every commit kind any envelope of this cascade produced — feeds the tick trailer */
        private val allKinds = mutableSetOf<Kind>()

        fun render(): String {
            sb.appendLine("sequenceDiagram")
            sb.appendLine("    actor Caller")
            sb.appendLine("    participant S as $systemName")
            sb.appendLine("    Caller->>S: commit$act(${params()})")
            sb.appendLine("    Note over Caller,S: boundary validation first — type checks and the input-constrained nevers compiled to this expose site, a violation is a refusal and nothing begins")

            val deferred = mutableListOf<Pair<RuleDecl, String>>() // after-commit firings this envelope caused
            renderEnvelope("the $act envelope", deferred, noteIfQuiet = true) {
                sb.appendLine("        S->>S: insert $act")
                if (act in model.transients)
                    sb.appendLine("        Note over S: transient act — its partitions are decided once, at this commit, and the instance is removed at the envelope's close (only consequences persist)")
                listOf(Kind.Create(act))
            }
            sb.appendLine("    S-->>Caller: accepted — or an error anywhere in the frame rolled the whole envelope back")

            // after-commit boundaries: each firing is its own transaction, begun after
            // the trigger is durable; its own consequences may defer further firings
            var wave = deferred.toList()
            var safety = 0
            while (wave.isNotEmpty() && safety++ < 8) {
                val next = mutableListOf<Pair<RuleDecl, String>>()
                for ((rule, cause) in wave) {
                    sb.appendLine("    S-)S: after commit — ${rule.name} begins its own transaction ($cause)")
                    renderEnvelope("${rule.name} firing", next) { renderFiring(rule, next) }
                    for (schedule in rule.triggers.filter { it != "commit" })
                        sb.appendLine("    Note right of S: backstop — every $schedule tick re-checks ${cond(rule)} and heals anything the boundary dropped, the guard makes re-evaluation harmless")
                }
                wave = next
            }

            tickTrailer()
            return sb.toString()
        }

        /** One transaction frame: the opening block renders its own lines and returns
         *  the commit kinds that seed the in-envelope cascade; transaction-end never
         *  notes close the frame. */
        private fun renderEnvelope(
            label: String,
            deferred: MutableList<Pair<RuleDecl, String>>,
            noteIfQuiet: Boolean = false,
            opening: () -> List<Kind>,
        ) {
            txnCount++
            val touched = mutableSetOf<String>()
            sb.appendLine("    critical T$txnCount — ${esc(label)}")
            val seed = opening()
            val queue = ArrayDeque(seed)
            seed.forEach { note(it, touched) }
            var fizzle = true
            while (queue.isNotEmpty()) {
                val k = queue.removeFirst()
                for (rule in model.rules.values) {
                    if (rule.name in fired || !affects(k, rule)) continue
                    when {
                        firesOnCommit(rule) -> {
                            fired.add(rule.name)
                            fizzle = false
                            val produced = renderFiring(rule, deferred)
                            produced.forEach { queue.add(it); note(it, touched) }
                        }
                        firesAfterCommit(rule) -> {
                            fired.add(rule.name)
                            deferred.add(rule to "triggered by ${describe(k)}")
                        }
                    }
                }
            }
            if (fizzle && noteIfQuiet) sb.appendLine("        Note over S: no rules fire inside this envelope")
            for (never in model.nevers) {
                val reads = model.summaryOfRefExpr(never.target).touchedShapes().map { model.baseOf(it) ?: it }
                if (reads.any { it in touched })
                    sb.appendLine("        Note over S: transaction-end check — never ${esc(Printer.refExpr(never.target))}")
            }
            sb.appendLine("    end")
        }

        /** Renders a firing's note + body statements; returns the commit kinds the body produces. */
        private fun renderFiring(rule: RuleDecl, deferred: MutableList<Pair<RuleDecl, String>>): List<Kind> {
            val leaving = if (rule.leaving) "when leaving" else "when"
            sb.appendLine("        Note over S: ${rule.name} — $leaving ${cond(rule)}")
            val produced = producedKinds(rule)
            for (item in rule.body) when (item) {
                is Creation -> sb.appendLine("        S->>S: insert ${item.shape}")
                is Assignment -> sb.appendLine("        S->>S: ${esc(Printer.expr(item.target))} = ${esc(Printer.expr(item.value))}")
                ThenMarker -> {}
            }
            return produced
        }

        /** Tick-only rules this cascade's commits can affect: what the next tick may pick up. */
        private fun tickTrailer() {
            for (rule in model.rules.values) {
                if (rule.name in fired) continue
                if (firesOnCommit(rule) || firesAfterCommit(rule)) continue
                val schedules = rule.triggers.filter { it != "commit" }
                if (schedules.isEmpty()) continue
                if (allKinds.none { affects(it, rule) }) continue
                for (schedule in schedules)
                    sb.appendLine("    Note right of S: at each $schedule tick — ${rule.name} sweeps current members of ${cond(rule)} in its own transaction per record")
            }
        }

        // ── firing model (V3's affects, widened to the runtime's relevance view) ─

        private fun firesOnCommit(r: RuleDecl) =
            r.preposition == null || (r.preposition == "on" && "commit" in r.triggers)

        private fun firesAfterCommit(r: RuleDecl) =
            r.preposition == "after" && "commit" in r.triggers

        private val summaries = mutableMapOf<String, ReadSummary>()
        private fun condSummary(rule: RuleDecl): ReadSummary =
            summaries.getOrPut(rule.name) { model.summaryOfRefExpr(rule.condition) }

        private fun affects(k: Kind, rule: RuleDecl): Boolean {
            val base = model.baseOfExpr(rule.condition) ?: return false
            if (base in model.transients) return k is Kind.Create && k.shape == base
            val s = condSummary(rule)
            if (s.opaque) return true
            return when (k) {
                is Kind.Create ->
                    // creating the base shape is an entry (born a member) but never an
                    // exit — a new instance has no prior membership to leave
                    (k.shape == base && !rule.leaving) || k.shape in s.existsShapes || k.shape in s.collShapes ||
                        s.fields.any { it.first == k.shape } || s.collFields.any { it.first == k.shape }
                is Kind.Assign ->
                    (k.shape to k.field) in s.fields || (k.shape to k.field) in s.collFields
            }
        }

        private fun producedKinds(rule: RuleDecl): List<Kind> {
            val subject = (rule.condition as? RefName)?.name ?: model.baseOfExpr(rule.condition)
            val out = mutableListOf<Kind>()
            for (item in rule.body) when (item) {
                is Creation -> out.add(Kind.Create(item.shape))
                is Assignment -> {
                    val t = item.target
                    val ownerScope =
                        if (t.segs.isEmpty()) subject
                        else model.pathElementShape(PathExpr(t.root, t.segs.dropLast(1)), subject ?: continue)
                    val owner = ownerScope?.let { model.baseOf(it) } ?: continue
                    val field = if (t.segs.isEmpty()) t.root else t.segs.last().name
                    out.add(Kind.Assign(owner, field))
                }
                ThenMarker -> {}
            }
            return out
        }

        private fun note(k: Kind, touched: MutableSet<String>) {
            allKinds.add(k)
            when (k) {
                is Kind.Create -> touched.add(k.shape)
                is Kind.Assign -> touched.add(k.shape)
            }
        }

        private fun describe(k: Kind) = when (k) {
            is Kind.Create -> "the ${k.shape} created above"
            is Kind.Assign -> "the write to ${k.shape}.${k.field}"
        }

        private fun cond(rule: RuleDecl) = esc(Printer.refExpr(rule.condition))

        /** Committer-supplied fields: stored props without an initializer (timestamps
         *  and `initially` fields are language- or spec-populated). */
        private fun params(): String =
            model.shapes[act]?.members
                ?.filterIsInstance<StoredProp>()?.filter { it.initially == null }
                ?.joinToString(", ") { it.name } ?: ""

        /** Mermaid line-content hygiene: '#' opens an entity code, ';' ends a statement. */
        private fun esc(s: String) = s.replace("#", "no.").replace(";", ",")
    }
}
