# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/AssignAdvisorSpec.kt. Regenerate with: gradle generate
Feature: AssignAdvisor

  # rule ApplyAdvisor
  Scenario: A new AssignAdvisor sets students.advisor
    When a commit brings one new assignAdvisor into "AssignAdvisor"
    Then that assignAdvisor is an "AssignAdvisor"
