# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/CourseSpec.kt. Regenerate with: gradle generate
Feature: Course

  # never (Course where capacity < 0)
  Scenario: A Course where capacity below 0 is refused
    When a "Course" with capacity -1 is committed
    Then it is refused
    And nothing has committed

  # never (Course where capacity < 0)
  Scenario: A Course with capacity 0 is accepted
    When a "Course" with capacity 0 is committed
    Then it is accepted
