# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/DropSpec.kt. Regenerate with: gradle generate
Feature: Drop

  # rule ApplyDrop
  Scenario: A new Drop sets student.courses
    When a commit brings one new drop into "Drop"
    Then that drop is a "Drop"
