# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/EnrollSpec.kt. Regenerate with: gradle generate
Feature: Enroll

  # rule ApplyEnroll
  Scenario: A new Enroll sets student.courses
    When a commit brings one new enroll into "Enroll"
    Then that enroll is an "Enroll"
