# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/SetEnrollmentSpec.kt. Regenerate with: gradle generate
Feature: SetEnrollment

  # rule ApplyEnrollmentSet
  Scenario: A new SetEnrollment sets student.courses
    When a commit brings one new setEnrollment into "SetEnrollment"
    Then that setEnrollment is a "SetEnrollment"
