# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/TagSpec.kt. Regenerate with: gradle generate
Feature: Tag

  # rule ApplyTag
  Scenario: A new Tag sets student.tags
    When a commit brings one new tag into "Tag"
    Then that tag is a "Tag"
