// The partition-drift exhibit's transpile output. This example exists to
// demonstrate a defect (the drift-exposed bare act partition) — see the spec's
// header and DriftDemonstrationTest. Regenerated by `gradle generate`.
plugins {
    kotlin("jvm")
}

group = "velle"

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":compiler"))
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

tasks.register<JavaExec>("generate") {
    description = "Regenerate the PartitionDrift typed surface and executable specs from partition_drift.velle"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("velle.GenerateKt")
    args("../partition_drift.velle", "PartitionDrift")
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
