# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/OrderLineSpec.kt. Regenerate with: gradle generate
Feature: OrderLine

  # rule ReserveStock
  Scenario: A new OrderLine produces a Reservation
    When a commit brings one new orderLine into "OrderLine"
    Then one more "Reservation" exists
    And that Reservation's "line" is the orderLine
