// The loyalty example's transpile output: developer-owned generated source
// and the tests that drive it. This example puts the prover's vocabulary on
// display in business terms — the predecessor recurrence with its descent
// certificate (checks.md V14), a `never` spent as both an acyclicity
// certificate and the instance-aliasing discharge (V1/V15), a pinned
// condition-only sibling read, and same-direction sibling prerequisites.
// Regenerated by `gradle generate`.
plugins {
    kotlin("jvm")
}

group = "velle"

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":compiler"))
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

tasks.register<JavaExec>("generate") {
    description = "Regenerate the Loyalty typed surface and executable specs from loyalty.velle"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("velle.GenerateKt")
    args("../loyalty.velle", "Loyalty")
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
