# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/ChangeEmailSpec.kt. Regenerate with: gradle generate
Feature: ChangeEmail

  # rule RecordEmailChange
  Scenario: A new ChangeEmail produces an EmailChange
    When a commit brings one new changeEmail into "ChangeEmail"
    Then one more "EmailChange" exists
