# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/ClosedTicketSpec.kt. Regenerate with: gradle generate
Feature: ClosedTicket

  # rule NoticeReopen
  Scenario: A ReopenTicket for a ClosedTicket produces a ReopenNotice
    Given a member of "ClosedTicket"
    When a "ReopenTicket" for it is committed
    Then it is no longer a "ClosedTicket"
    And one more "ReopenNotice" exists
    And that ReopenNotice's "ticket" is the ticket

  # rule ApplyAssignment
  Scenario: A new ApplicableAssignment sets ticket.assignee
    When a commit brings one new assignTicket into "ApplicableAssignment"
    Then the ticket.assignee now equals the act's "agent"
    And the act is in exactly one of "ApplicableAssignment" / "RefusedAssignment"

  # rule RecordAssignmentRefusal
  Scenario: A new RefusedAssignment produces an AssignmentRefusal
    When a commit brings one new assignTicket into "RefusedAssignment"
    Then one more "AssignmentRefusal" exists
    And that AssignmentRefusal's "attempt" is the assignTicket
    And the act is in exactly one of "RefusedAssignment" / "ApplicableAssignment"

  # rule EscalateUrgent
  Scenario: At the Daily tick, an UrgentQueue produces an Escalation
    Given one ticket in "UrgentQueue", no "Daily" tick yet
    When "Daily" ticks
    Then one more "Escalation" exists
    And that Escalation's "ticket" is the ticket
    And another "Daily" tick produces nothing more
    And after 3 days pass, "Daily" produces another "Escalation"
