# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/CloseTicketSpec.kt. Regenerate with: gradle generate
Feature: CloseTicket

  # rule RecordTicketClosure
  Scenario: A new CloseTicket produces a TicketClosure
    When a commit brings one new closeTicket into "CloseTicket"
    Then one more "TicketClosure" exists
