# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/DelinquentSpec.kt. Regenerate with: gradle generate
Feature: Delinquent

  # rule TrackLowestBalance
  Scenario: A new Delinquent sets lowestBalance
    When a commit brings one new member into "Delinquent"
    Then that member is a "Delinquent"

  # rule SuspendDelinquents
  Scenario: At the Nightly tick, a Delinquent sets suspended
    Given one member in "Delinquent", no "Nightly" tick yet
    When "Nightly" ticks
    Then the sweep has run for every current member

  # rule OpenDelinquencyEpisode
  Scenario: A new Delinquent produces a DelinquencyFlag
    When a commit brings one new member into "Delinquent"
    Then one more "DelinquencyFlag" exists
    And that DelinquencyFlag's "member" is the member

  # rule CloseDelinquencyEpisode
  Scenario: A member that leaves Delinquent produces a DelinquencyResolution
    Given a member of "Delinquent"
    When the commit that takes it out of "Delinquent" lands
    Then it is no longer a "Delinquent"
    And one more "DelinquencyResolution" exists
