# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/DepositSpec.kt. Regenerate with: gradle generate
Feature: Deposit

  # never (Deposit where amount <= 0)
  Scenario: A Deposit where amount at most 0 is refused
    Given any committed "Member"
    When a "Deposit" with amount -1 is committed
    Then it is refused
    And nothing has committed

  # never (Deposit where amount <= 0)
  Scenario: A Deposit with amount 1 is accepted
    Given any committed "Member"
    When a "Deposit" with amount 1 is committed
    Then it is accepted
