# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/MakeDepositSpec.kt. Regenerate with: gradle generate
Feature: MakeDeposit

  # rule RecordDeposit
  Scenario: A new MakeDeposit produces a Deposit
    When a commit brings one new makeDeposit into "MakeDeposit"
    Then one more "Deposit" exists

  # rule ApplyDeposit
  Scenario: A new UnappliedDeposit sets member.balance and applied after the commit
    When a commit brings one new deposit into "UnappliedDeposit"
    Then the rule has fired after that transaction
    And the deposit has left "UnappliedDeposit"

  # never (MakeDeposit where amount <= 0)
  Scenario: A MakeDeposit where amount at most 0 is refused
    Given any committed "Member"
    When a "MakeDeposit" with amount -1 is committed
    Then it is refused
    And nothing has committed

  # never (MakeDeposit where amount <= 0)
  Scenario: A MakeDeposit with amount 1 is accepted
    Given any committed "Member"
    When a "MakeDeposit" with amount 1 is committed
    Then it is accepted
