# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/MemberSpec.kt. Regenerate with: gradle generate
Feature: Member

  # rule SendWelcome
  Scenario: A new Member produces a WelcomeNote
    When a commit brings one new member into "Member"
    Then one more "WelcomeNote" exists

  # rule RestoreService
  Scenario: At the Nightly tick, a Member sets suspended
    Given one member in "Member", no "Nightly" tick yet
    When "Nightly" ticks
    Then the sweep has run for every current member

  # rule ScoreEngagement
  Scenario: At the Nightly tick, a Member sets engagementScore
    Given one member in "Member", no "Nightly" tick yet
    When "Nightly" ticks
    Then the sweep has run for every current member
