# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/RaiseTicketSpec.kt. Regenerate with: gradle generate
Feature: RaiseTicket

  # rule FileTicket
  Scenario: A new RaiseTicket produces a Ticket
    When a commit brings one new raiseTicket into "RaiseTicket"
    Then one more "Ticket" exists

  # rule NoticeReopen
  Scenario: A ReopenTicket for a ClosedTicket produces a ReopenNotice
    Given a member of "ClosedTicket"
    When a "ReopenTicket" for it is committed
    Then it is no longer a "ClosedTicket"
    And one more "ReopenNotice" exists
    And that ReopenNotice's "ticket" is the ticket

  # rule ApplyAssignment
  Scenario: A new ApplicableAssignment sets ticket.assignee
    When a commit brings one new assignTicket into "ApplicableAssignment"
    Then the ticket.assignee now equals the act's "agent"

  # rule EscalateUrgent
  Scenario: At the Daily tick, an UrgentQueue produces an Escalation
    Given one ticket in "UrgentQueue", no "Daily" tick yet
    When "Daily" ticks
    Then one more "Escalation" exists
    And that Escalation's "ticket" is the ticket
    And another "Daily" tick produces nothing more
    And after 3 days pass, "Daily" produces another "Escalation"
