# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/SignUpSpec.kt. Regenerate with: gradle generate
Feature: SignUp

  # rule AdmitMember
  Scenario: A new SignUp produces a Member
    When a commit brings one new signUp into "SignUp"
    Then one more "Member" exists

  # rule RenewMembership
  Scenario: At the Monthly tick, an ActiveMember produces a Charge
    Given one member in "ActiveMember", no "Monthly" tick yet
    When "Monthly" ticks
    Then one more "Charge" exists
    And that Charge's "member" is the member
    And another "Monthly" tick produces nothing more
    And after 31 days pass, "Monthly" produces another "Charge"

  # rule ApplyCharge
  Scenario: A new UnappliedCharge produces a ChargeApplication and sets member.balance after the commit
    When a commit brings one new charge into "UnappliedCharge"
    Then the rule has fired after that transaction
    And one more "ChargeApplication" exists
    And that ChargeApplication's "charge" is the charge
    And the charge has left "UnappliedCharge"
    And another "Hourly" tick produces nothing more

  # rule TrackLowestBalance
  Scenario: A new Delinquent sets lowestBalance
    When a commit brings one new member into "Delinquent"
    Then that member is a "Delinquent"

  # rule SuspendDelinquents
  Scenario: At the Nightly tick, a Delinquent sets suspended
    Given one member in "Delinquent", no "Nightly" tick yet
    When "Nightly" ticks
    Then the sweep has run for every current member

  # rule OpenDelinquencyEpisode
  Scenario: A new Delinquent produces a DelinquencyFlag
    When a commit brings one new member into "Delinquent"
    Then one more "DelinquencyFlag" exists
    And that DelinquencyFlag's "member" is the member

  # rule CloseDelinquencyEpisode
  Scenario: A member that leaves Delinquent produces a DelinquencyResolution
    Given a member of "Delinquent"
    When the commit that takes it out of "Delinquent" lands
    Then it is no longer a "Delinquent"
    And one more "DelinquencyResolution" exists

  # rule OpenAccountReview
  Scenario: A new ChronicDelinquent produces an AuditEntry and an AccountReview
    When a commit brings one new member into "ChronicDelinquent"
    Then one more "AuditEntry" exists
    And that AuditEntry's "member" is the member
    And one more "AccountReview" exists
    And that AccountReview's "member" is the member
    And another "Daily" tick produces nothing more
