# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/UnappliedDepositSpec.kt. Regenerate with: gradle generate
Feature: UnappliedDeposit

  # rule ApplyDeposit
  Scenario: A new UnappliedDeposit sets member.balance and applied after the commit
    When a commit brings one new deposit into "UnappliedDeposit"
    Then the rule has fired after that transaction
    And the deposit has left "UnappliedDeposit"
