# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/VisitSpec.kt. Regenerate with: gradle generate
Feature: Visit

  # rule CountVisit
  Scenario: A new Visit sets member.visitCount
    When a commit brings one new visit into "Visit"
    Then that visit is a "Visit"

  # rule PingAnalytics
  Scenario: A new Visit produces an AnalyticsPing
    When a commit brings one new visit into "Visit"
    Then one more "AnalyticsPing" exists
    And that AnalyticsPing's "visit" is the visit

  # never (Visit where minutes <= 0)
  Scenario: A Visit where minutes at most 0 is refused
    Given any committed "Member"
    When a "Visit" with minutes -1 is committed
    Then it is refused
    And nothing has committed

  # never (Visit where minutes <= 0)
  Scenario: A Visit with minutes 1 is accepted
    Given any committed "Member"
    When a "Visit" with minutes 1 is committed
    Then it is accepted
