# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/CertifiedMemberSpec.kt. Regenerate with: gradle generate
Feature: CertifiedMember

  # rule IssueKeycard
  Scenario: A new CertifiedMember produces a Keycard
    When a commit brings one new member into "CertifiedMember"
    Then one more "Keycard" exists
    And that Keycard's "member" is the member
