# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/EnrollmentSpec.kt. Regenerate with: gradle generate
Feature: Enrollment

  # rule FileWaiver
  Scenario: A new Enrollment produces a SafetyWaiver
    When a commit brings one new enrollment into "Enrollment"
    Then one more "SafetyWaiver" exists

  # rule BookOrientation
  Scenario: A new Enrollment produces an OrientationRecord
    When a commit brings one new enrollment into "Enrollment"
    Then one more "OrientationRecord" exists
