# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/JoinSpec.kt. Regenerate with: gradle generate
Feature: Join

  # rule AdmitMember
  Scenario: A new Join produces a Member
    When a commit brings one new join into "Join"
    Then one more "Member" exists

  # rule IssueKeycard
  Scenario: A new CertifiedMember produces a Keycard
    When a commit brings one new member into "CertifiedMember"
    Then one more "Keycard" exists
    And that Keycard's "member" is the member
