# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/PurchaseSpec.kt. Regenerate with: gradle generate
Feature: Purchase

  # never (Purchase where amount <= 0)
  Scenario: A Purchase where amount at most 0 is refused
    Given any committed "Member"
    When a "Purchase" with amount -1 is committed
    Then it is refused
    And nothing has committed

  # never (Purchase where amount <= 0)
  Scenario: A Purchase with amount 1 is accepted
    Given any committed "Member"
    When a "Purchase" with amount 1 is committed
    Then it is accepted
