# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/QualifiedPurchaseSpec.kt. Regenerate with: gradle generate
Feature: QualifiedPurchase

  # rule PromoteBuyer
  Scenario: A new QualifiedPurchase sets member.tier
    When a commit brings one new purchase into "QualifiedPurchase"
    Then that purchase is a "QualifiedPurchase"

  # rule PromoteReferrer
  Scenario: A new QualifiedPurchase sets member.referrer.tier
    When a commit brings one new purchase into "QualifiedPurchase"
    Then that purchase is a "QualifiedPurchase"
