# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/VipPurchaseSpec.kt. Regenerate with: gradle generate
Feature: VipPurchase

  # rule ThankVip
  Scenario: A new VipPurchase produces a ThankYouNote
    When a commit brings one new purchase into "VipPurchase"
    Then one more "ThankYouNote" exists
    And that ThankYouNote's "purchase" is the purchase
