# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/CreateNoteSpec.kt. Regenerate with: gradle generate
Feature: CreateNote

  # rule MaterializeNote
  Scenario: A new CreateNote produces a Note
    When a commit brings one new createNote into "CreateNote"
    Then one more "Note" exists

  # rule ApplyBareEdit
  Scenario: A new ApplicableBareEdit sets note.body
    When a commit brings one new bareEdit into "ApplicableBareEdit"
    Then the note.body now equals the act's "newText"
    And the act is in exactly one of "ApplicableBareEdit" / "RefusedBareEdit"

  # rule RefuseBareEdit
  Scenario: A new RefusedBareEdit produces a BareEditRefusal
    When a commit brings one new bareEdit into "RefusedBareEdit"
    Then one more "BareEditRefusal" exists
    And that BareEditRefusal's "edit" is the bareEdit
    And the act is in exactly one of "RefusedBareEdit" / "ApplicableBareEdit"

  # rule ApplySafeEdit
  Scenario: A new ApplicableSafeEdit produces an EditApplication and sets note.title
    When a commit brings one new safeEdit into "ApplicableSafeEdit"
    Then one more "EditApplication" exists
    And that EditApplication's "edit" is the safeEdit
    And the note.title now equals the act's "newTitle"

  # rule RefuseSafeEdit
  Scenario: A new RefusedSafeEdit produces an EditRefusal
    When a commit brings one new safeEdit into "RefusedSafeEdit"
    Then one more "EditRefusal" exists
    And that EditRefusal's "edit" is the safeEdit

  # rule ApplyTransientEdit
  Scenario: A new ApplicableTransientEdit sets note.title
    When a commit brings one new transientEdit into "ApplicableTransientEdit"
    Then the note.title now equals the act's "newTitle"
    And the act is in exactly one of "ApplicableTransientEdit" / "RefusedTransientEdit"

  # rule RefuseTransientEdit
  Scenario: A new RefusedTransientEdit produces a TransientEditRefusal
    When a commit brings one new transientEdit into "RefusedTransientEdit"
    Then one more "TransientEditRefusal" exists
    And the act is in exactly one of "RefusedTransientEdit" / "ApplicableTransientEdit"
