# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/LockNoteSpec.kt. Regenerate with: gradle generate
Feature: LockNote

  # rule ApplyLock
  Scenario: A new LockNote sets note.locked
    When a commit brings one new lockNote into "LockNote"
    Then that lockNote is a "LockNote"
