# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/RenameTextSpec.kt. Regenerate with: gradle generate
Feature: RenameText

  # rule ApplyRename
  Scenario: A new RenameText sets note.body
    When a commit brings one new renameText into "RenameText"
    Then the note.body now equals the act's "newText"
