# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/UnlockNoteSpec.kt. Regenerate with: gradle generate
Feature: UnlockNote

  # rule ApplyUnlock
  Scenario: A new UnlockNote sets note.locked
    When a commit brings one new unlockNote into "UnlockNote"
    Then that unlockNote is an "UnlockNote"
