# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/CardUpdateSpec.kt. Regenerate with: gradle generate
Feature: CardUpdate

  # rule ApplyCardUpdate
  Scenario: A new CardUpdate sets customer.card
    When a commit brings one new cardUpdate into "CardUpdate"
    Then the customer.card now equals the act's "card"
