# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/ChargeableOrderSpec.kt. Regenerate with: gradle generate
Feature: ChargeableOrder

  # rule RequestInitialCharge
  Scenario: A new ChargeableOrder produces a ChargeAttempt
    When a commit brings one new order into "ChargeableOrder"
    Then one more "ChargeAttempt" exists
    And that ChargeAttempt's "order" is the order

  # rule TimeOutStaleAttempt
  Scenario: At the QuarterHourly tick, a StalePendingAttempt produces an AttemptTimeout
    Given one chargeAttempt in "StalePendingAttempt", no "QuarterHourly" tick yet
    When "QuarterHourly" ticks
    Then one more "AttemptTimeout" exists
    And that AttemptTimeout's "attempt" is the chargeAttempt
    And another "QuarterHourly" tick produces nothing more

  # rule SendReceipt
  Scenario: A new SuccessfulCharge produces a Receipt
    When a commit brings one new chargeAttempt into "SuccessfulCharge"
    Then one more "Receipt" exists
    And that Receipt's "attempt" is the chargeAttempt
