# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/ExhaustedOrderSpec.kt. Regenerate with: gradle generate
Feature: ExhaustedOrder

  # rule ReleaseStockOnExhaustion
  Scenario: A new ExhaustedOrder produces a ReservationRelease
    When a commit brings one new order into "ExhaustedOrder"
    Then one more "ReservationRelease" exists
