# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/ExhaustedOrderSpec.kt. Regenerate with: gradle generate
Feature: ExhaustedOrder

  # rule ReleaseStockOnExhaustion
  Scenario: A new ExhaustedOrder produces a ReservationRelease after the commit
    When a commit brings one new order into "ExhaustedOrder"
    Then the rule has fired after that transaction
    And one more "ReservationRelease" exists
    And the order has left "ExhaustedOrder"
    And another "Nightly" tick produces nothing more
