# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/ExtensionRequestSpec.kt. Regenerate with: gradle generate
Feature: ExtensionRequest

  # rule GrantGracePeriod
  Scenario: A new ExtensionRequest produces a PaymentExtension
    When a commit brings one new extensionRequest into "ExtensionRequest"
    Then one more "PaymentExtension" exists
