# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/IssueRefundSpec.kt. Regenerate with: gradle generate
Feature: IssueRefund

  # rule RecordRefund
  Scenario: A new IssueRefund produces a Refund
    When a commit brings one new issueRefund into "IssueRefund"
    Then one more "Refund" exists

  # never (IssueRefund where amount <= 0)
  Scenario: A IssueRefund where amount at most 0 is refused
    Given any committed "Order"
    When a "IssueRefund" with amount -1 is committed
    Then it is refused
    And nothing has committed

  # never (IssueRefund where amount <= 0)
  Scenario: A IssueRefund with amount 1 is accepted
    Given any committed "Order"
    When a "IssueRefund" with amount 1 is committed
    Then it is accepted
