# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/ManualChargeSpec.kt. Regenerate with: gradle generate
Feature: ManualCharge

  # rule ApplyManualCharge
  Scenario: A new ManualCharge produces a ChargeAttempt
    When a commit brings one new manualCharge into "ManualCharge"
    Then one more "ChargeAttempt" exists
