# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/OrderSpec.kt. Regenerate with: gradle generate
Feature: Order

  # rule ReserveStock
  Scenario: A new Order produces a StockReservation
    When a commit brings one new order into "Order"
    Then one more "StockReservation" exists
    And that StockReservation's "order" is the order
