# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/PlaceOrderSpec.kt. Regenerate with: gradle generate
Feature: PlaceOrder

  # rule AcceptOrder
  Scenario: A new PlaceOrder produces an Order
    When a commit brings one new placeOrder into "PlaceOrder"
    Then one more "Order" exists

  # rule RequestInitialCharge
  Scenario: A new ChargeableOrder produces a ChargeAttempt
    When a commit brings one new order into "ChargeableOrder"
    Then one more "ChargeAttempt" exists
    And that ChargeAttempt's "order" is the order

  # rule RetryCharge
  Scenario: A new RetryableOrder produces a ChargeAttempt
    When a commit brings one new order into "RetryableOrder"
    Then one more "ChargeAttempt" exists
    And that ChargeAttempt's "order" is the order

  # rule TimeOutStaleAttempt
  Scenario: At the QuarterHourly tick, a StalePendingAttempt produces an AttemptTimeout
    Given one chargeAttempt in "StalePendingAttempt", no "QuarterHourly" tick yet
    When "QuarterHourly" ticks
    Then one more "AttemptTimeout" exists
    And that AttemptTimeout's "attempt" is the chargeAttempt
    And another "QuarterHourly" tick produces nothing more

  # rule ReleaseStockOnExhaustion
  Scenario: A new ExhaustedOrder produces a ReservationRelease after the commit
    When a commit brings one new order into "ExhaustedOrder"
    Then the rule has fired after that transaction
    And one more "ReservationRelease" exists
    And the order has left "ExhaustedOrder"
    And another "Nightly" tick produces nothing more

  # rule SendReceipt
  Scenario: A new SuccessfulCharge produces a Receipt
    When a commit brings one new chargeAttempt into "SuccessfulCharge"
    Then one more "Receipt" exists
    And that Receipt's "attempt" is the chargeAttempt

  # rule ShipOrder
  Scenario: At the Nightly tick, a ReadyToShip produces a Shipment
    Given one order in "ReadyToShip", no "Nightly" tick yet
    When "Nightly" ticks
    Then one more "Shipment" exists
    And that Shipment's "order" is the order
    And another "Nightly" tick produces nothing more

  # rule ApplyAddressChange
  Scenario: A new ApplicableAddressChange produces an AddressChangeApplication and sets order.shippingAddress
    When a commit brings one new changeShippingAddress into "ApplicableAddressChange"
    Then one more "AddressChangeApplication" exists
    And that AddressChangeApplication's "change" is the changeShippingAddress
    And the order.shippingAddress now equals the act's "newAddress"

  # rule RecordAddressRefusal
  Scenario: A new RefusedAddressChange produces an AddressChangeRefusal
    When a commit brings one new changeShippingAddress into "RefusedAddressChange"
    Then one more "AddressChangeRefusal" exists
    And that AddressChangeRefusal's "change" is the changeShippingAddress

  # rule NoteSettlementReversal
  Scenario: An order that leaves SettledOrder produces a SettlementReversal
    Given a member of "SettledOrder"
    When the commit that takes it out of "SettledOrder" lands
    Then it is no longer a "SettledOrder"
    And one more "SettlementReversal" exists
    And that SettlementReversal's "order" is the order

  # rule RemindPayment
  Scenario: At the Daily tick, an OverdueOrder produces a PaymentReminder
    Given one order in "OverdueOrder", no "Daily" tick yet
    When "Daily" ticks
    Then one more "PaymentReminder" exists
    And that PaymentReminder's "order" is the order
    And another "Daily" tick produces nothing more
    And after 4 days pass, "Daily" produces another "PaymentReminder"

  # rule OpenDunningEpisode
  Scenario: A new OverdueOrder produces a DunningFlag
    When a commit brings one new order into "OverdueOrder"
    Then one more "DunningFlag" exists
    And that DunningFlag's "order" is the order
    And another "Daily" tick produces nothing more

  # rule CloseDunningEpisode
  Scenario: At the Daily tick, a ClosableDunningFlag produces a DunningResolution
    Given one dunningFlag in "ClosableDunningFlag", no "Daily" tick yet
    When "Daily" ticks
    Then one more "DunningResolution" exists
    And that DunningResolution's "flag" is the dunningFlag
    And another "Daily" tick produces nothing more

  # never (PlaceOrder where amount <= 0)
  Scenario: A PlaceOrder where amount at most 0 is refused
    Given any committed "Customer"
    When a "PlaceOrder" with amount -1 is committed
    Then it is refused
    And nothing has committed

  # never (PlaceOrder where amount <= 0)
  Scenario: A PlaceOrder with amount 1 is accepted
    Given any committed "Customer"
    When a "PlaceOrder" with amount 1 is committed
    Then it is accepted
