# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/ProcessorVerdictSpec.kt. Regenerate with: gradle generate
Feature: ProcessorVerdict

  # rule RecordVerdict
  Scenario: A new ProcessorVerdict produces a ChargeResponse
    When a commit brings one new processorVerdict into "ProcessorVerdict"
    Then one more "ChargeResponse" exists
