# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/RefundSpec.kt. Regenerate with: gradle generate
Feature: Refund

  # never (Refund where amount <= 0)
  Scenario: A Refund where amount at most 0 is refused
    Given any committed "Order"
    When a "Refund" with amount -1 is committed
    Then it is refused
    And nothing has committed

  # never (Refund where amount <= 0)
  Scenario: A Refund with amount 1 is accepted
    Given any committed "Order"
    When a "Refund" with amount 1 is committed
    Then it is accepted
