# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/RetryableOrderSpec.kt. Regenerate with: gradle generate
Feature: RetryableOrder

  # rule RetryCharge
  Scenario: A new RetryableOrder produces a ChargeAttempt
    When a commit brings one new order into "RetryableOrder"
    Then one more "ChargeAttempt" exists
    And that ChargeAttempt's "order" is the order
