# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/SettledOrderSpec.kt. Regenerate with: gradle generate
Feature: SettledOrder

  # rule ShipOrder
  Scenario: At the Nightly tick, a ReadyToShip produces a Shipment
    Given one order in "ReadyToShip", no "Nightly" tick yet
    When "Nightly" ticks
    Then one more "Shipment" exists
    And that Shipment's "order" is the order
    And another "Nightly" tick produces nothing more

  # rule ApplyAddressChange
  Scenario: A new ApplicableAddressChange produces an AddressChangeApplication and sets order.shippingAddress
    When a commit brings one new changeShippingAddress into "ApplicableAddressChange"
    Then one more "AddressChangeApplication" exists
    And that AddressChangeApplication's "change" is the changeShippingAddress
    And the order.shippingAddress now equals the act's "newAddress"

  # rule RecordAddressRefusal
  Scenario: A new RefusedAddressChange produces an AddressChangeRefusal
    When a commit brings one new changeShippingAddress into "RefusedAddressChange"
    Then one more "AddressChangeRefusal" exists
    And that AddressChangeRefusal's "change" is the changeShippingAddress

  # rule NoteSettlementReversal
  Scenario: An order that leaves SettledOrder produces a SettlementReversal
    Given a member of "SettledOrder"
    When the commit that takes it out of "SettledOrder" lands
    Then it is no longer a "SettledOrder"
    And one more "SettlementReversal" exists
    And that SettlementReversal's "order" is the order
