# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/UnpaidOrderSpec.kt. Regenerate with: gradle generate
Feature: UnpaidOrder

  # rule RemindPayment
  Scenario: At the Daily tick, an OverdueOrder produces a PaymentReminder
    Given one order in "OverdueOrder", no "Daily" tick yet
    When "Daily" ticks
    Then one more "PaymentReminder" exists
    And that PaymentReminder's "order" is the order
    And another "Daily" tick produces nothing more
    And after 4 days pass, "Daily" produces another "PaymentReminder"

  # rule OpenDunningEpisode
  Scenario: A new OverdueOrder produces a DunningFlag
    When a commit brings one new order into "OverdueOrder"
    Then one more "DunningFlag" exists
    And that DunningFlag's "order" is the order
    And another "Daily" tick produces nothing more

  # rule CloseDunningEpisode
  Scenario: At the Daily tick, a ClosableDunningFlag produces a DunningResolution
    Given one dunningFlag in "ClosableDunningFlag", no "Daily" tick yet
    When "Daily" ticks
    Then one more "DunningResolution" exists
    And that DunningResolution's "flag" is the dunningFlag
    And another "Daily" tick produces nothing more
