// The orders example's transpile output: developer-owned generated source and
// the tests that drive it. This example exercises the exposure closure of
// README §6 "Inline part creation" — `expose ... with`, nested input types,
// language-populated back-references, per-part rule firings, the boundary
// refusal rolling back the whole closure, and the derived aggregate on the
// container. Regenerated by `gradle generate`.
plugins {
    kotlin("jvm")
}

group = "velle"

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":compiler"))
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

tasks.register<JavaExec>("generate") {
    description = "Regenerate the Orders typed surface and executable specs from orders.velle"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("velle.GenerateKt")
    args("../orders.velle", "Orders")
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
