# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/BillCustomerSpec.kt. Regenerate with: gradle generate
Feature: BillCustomer

  # rule OpenInvoice
  Scenario: A new BillCustomer produces an Invoice
    When a commit brings one new billCustomer into "BillCustomer"
    Then one more "Invoice" exists

  # rule SendReceipt
  Scenario: A new PaidInvoice produces a Receipt
    When a commit brings one new invoice into "PaidInvoice"
    Then one more "Receipt" exists
    And that Receipt's "invoice" is the invoice

  # rule EmailReceipt
  Scenario: A new UnemailedReceipt produces a ReceiptEmail after the commit
    When a commit brings one new receipt into "UnemailedReceipt"
    Then the rule has fired after that transaction
    And one more "ReceiptEmail" exists
    And that ReceiptEmail's "receipt" is the receipt
    And the receipt has left "UnemailedReceipt"
    And another "Hourly" tick produces nothing more

  # rule RemindOverdue
  Scenario: At the Weekly tick, an ActionableOverdue produces a Reminder
    Given one invoice in "ActionableOverdue", no "Weekly" tick yet
    When "Weekly" ticks
    Then one more "Reminder" exists
    And that Reminder's "invoice" is the invoice
    And another "Weekly" tick produces nothing more
    And after 8 days pass, "Weekly" produces another "Reminder"

  # rule ApplyDueChange
  Scenario: A new ApplicableDueChange sets invoice.due
    When a commit brings one new changeDueDate into "ApplicableDueChange"
    Then the invoice.due now equals the act's "newDue"
    And the act is in exactly one of "ApplicableDueChange" / "RefusedDueChange"

  # rule RecordDueChangeRefusal
  Scenario: A new RefusedDueChange produces a DueChangeRefusal
    When a commit brings one new changeDueDate into "RefusedDueChange"
    Then one more "DueChangeRefusal" exists
    And the act is in exactly one of "RefusedDueChange" / "ApplicableDueChange"

  # rule NoteUnarchival
  Scenario: An UnarchiveRequest for an ArchivedInvoice produces an UnarchiveNotice
    Given a member of "ArchivedInvoice"
    When a "UnarchiveRequest" for it is committed
    Then it is no longer a "ArchivedInvoice"
    And one more "UnarchiveNotice" exists
    And that UnarchiveNotice's "invoice" is the invoice
