# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/IssuedInvoiceSpec.kt. Regenerate with: gradle generate
Feature: IssuedInvoice

  # rule ApplyDueChange
  Scenario: A new ApplicableDueChange sets invoice.due
    When a commit brings one new changeDueDate into "ApplicableDueChange"
    Then the invoice.due now equals the act's "newDue"
    And the act is in exactly one of "ApplicableDueChange" / "RefusedDueChange"

  # rule RecordDueChangeRefusal
  Scenario: A new RefusedDueChange produces a DueChangeRefusal
    When a commit brings one new changeDueDate into "RefusedDueChange"
    Then one more "DueChangeRefusal" exists
    And that DueChangeRefusal's "change" is the changeDueDate
    And the act is in exactly one of "RefusedDueChange" / "ApplicableDueChange"
