# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/LineItemSpec.kt. Regenerate with: gradle generate
Feature: LineItem

  # never (LineItem where quantity <= 0)
  Scenario: A LineItem where quantity at most 0 is refused
    Given any committed "Invoice"
    When a "LineItem" with quantity -1 is committed
    Then it is refused
    And nothing has committed

  # never (LineItem where quantity <= 0)
  Scenario: A LineItem with quantity 1 is accepted
    Given any committed "Invoice"
    When a "LineItem" with quantity 1 is committed
    Then it is accepted

  # never (LineItem where price < 0)
  Scenario: A LineItem where price below 0 is refused
    Given any committed "Invoice"
    When a "LineItem" with price -1 is committed
    Then it is refused
    And nothing has committed

  # never (LineItem where price < 0)
  Scenario: A LineItem with price 0 is accepted
    Given any committed "Invoice"
    When a "LineItem" with price 0 is committed
    Then it is accepted
