# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/OverdueInvoiceSpec.kt. Regenerate with: gradle generate
Feature: OverdueInvoice

  # rule RemindOverdue
  Scenario: At the Weekly tick, an ActionableOverdue produces a Reminder
    Given one invoice in "ActionableOverdue", no "Weekly" tick yet
    When "Weekly" ticks
    Then one more "Reminder" exists
    And that Reminder's "invoice" is the invoice
    And another "Weekly" tick produces nothing more
    And after 8 days pass, "Weekly" produces another "Reminder"
