# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/PaidInvoiceSpec.kt. Regenerate with: gradle generate
Feature: PaidInvoice

  # rule SendReceipt
  Scenario: A new PaidInvoice produces a Receipt
    When a commit brings one new invoice into "PaidInvoice"
    Then one more "Receipt" exists
    And that Receipt's "invoice" is the invoice

  # rule EmailReceipt
  Scenario: A new UnemailedReceipt produces a ReceiptEmail after the commit
    When a commit brings one new receipt into "UnemailedReceipt"
    Then the rule has fired after that transaction
    And one more "ReceiptEmail" exists
    And that ReceiptEmail's "receipt" is the receipt
    And the receipt has left "UnemailedReceipt"
    And another "Hourly" tick produces nothing more
