# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/PaymentSpec.kt. Regenerate with: gradle generate
Feature: Payment

  # rule TrackLargestPayment
  Scenario: A new Payment sets invoice.customer.largestPayment
    When a commit brings one new payment into "Payment"
    Then that payment is a "Payment"
