# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/SignUpSpec.kt. Regenerate with: gradle generate
Feature: SignUp

  # rule AdmitCustomer
  Scenario: A new SignUp produces a Customer
    When a commit brings one new signUp into "SignUp"
    Then one more "Customer" exists
