# GENERATED by Velle from the spec — documentation, not a runner; the
# executable form is specs/SubmitPaymentSpec.kt. Regenerate with: gradle generate
Feature: SubmitPayment

  # rule RecordPayment
  Scenario: A new SubmitPayment produces a Payment
    When a commit brings one new submitPayment into "SubmitPayment"
    Then one more "Payment" exists

  # never (SubmitPayment where amount <= 0)
  Scenario: A SubmitPayment where amount at most 0 is refused
    Given any committed "Invoice"
    When a "SubmitPayment" with amount -1 is committed
    Then it is refused
    And nothing has committed

  # never (SubmitPayment where amount <= 0)
  Scenario: A SubmitPayment with amount 1 is accepted
    Given any committed "Invoice"
    When a "SubmitPayment" with amount 1 is committed
    Then it is accepted
