// The billing example's transpile output: developer-owned generated source and
// the tests that verify the runtime. Regenerated by `gradle generate`; separate
// from the compiler on purpose (README §22, "The extension framework").
plugins {
    kotlin("jvm")
}

group = "velle"

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":compiler"))
    // engineer-side storage for the hydration spike app (velle/app)
    implementation("org.xerial:sqlite-jdbc:3.47.1.0")
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

tasks.register<JavaExec>("runApp") {
    description = "Run the hydration spike app against a local SQLite db (billing.db)"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("velle.app.BillingAppKt")
}

tasks.register<JavaExec>("generate") {
    description = "Regenerate the Billing typed surface and executable specs from billing.velle"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("velle.GenerateKt")
    args("../billing.velle", "Billing")
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
